### ISSUE TITLE
Plex Backend Version

### ISSUE THREAD

**Issue by servusoft** [idelsink/ampache-docker#9] opened 2017-10-22 22:21 UTC
After installation:
```
Ampache
2 hours ago
0.9.9.13.525-197d5ed
Plex Media Server
Ampache
Linux (#1 SMP Debian 3.2.54-2)
```
but it not work, because the Web-App needs  at least Plex Media Server 1.3.0.
How to update Plex Media Server?

**Comment by idelsink** [comment] 2017-10-24 20:17
Hi,

I'm not sure what you mean. 
You mean the Plex Media Server package from your distro(debian)?

**Comment by servusoft** [comment] 2017-10-24 23:31
Sorry! 
I have an Plex player (installed on a Qnap-NAS) :
```
NAS4
6 minutes ago
1.7.5.4035-313f93718
Plex Media Server
PC
Linux 4.2.8 (#1 SMP Fri Sep 1 01:08:22 CST 2017)
```

and your ampache-docker (installed on a ubuntu - 4.4.0-97-generic #120-Ubuntu):
```
Ampache
2 days ago
0.9.9.13.525-197d5ed
Plex Media Server
Ampache
Linux (#1 SMP Debian 3.2.54-2)
```

With NAS ist works fine, but with the docker isn't.
It's needed at least version 1.3 and your docker has 0.9.9
The docker runs on alpine:3.4.
I have no idea, how to update the Plex Media Server (1.3 or newer)

**Comment by servusoft** [comment] 2017-10-25 08:58
I found an issue like this on ampache:
https://github.com/ampache/ampache/issues/1456
its may be an issue inside the ampache and not your docker.

**Comment by idelsink** [comment] 2017-10-27 20:03
Ah yes, it seems that it's a bug on the ampache end. I have never really tested it on a plex server. When I use plex, I use my phone and the plex android application. 
I will try to reproduce this on a later time (I will post my findings). I'm gonna close this issue for now, because I can't really do anything from my end. 

If you have any more information I would add it to the issue you linked.

**Closed as completed** 2017-10-27 20:03 UTC

**Comment by lockntross** [comment] 2018-12-17 04:33
**Same problem.** 
I'm using the docker file. [https://hub.docker.com/r/ampache/ampache/]
Plex connected and as soon as you try and access the Ampache share -- you're greeted with this:
`Update your Plex Media Server
The server "Ampache-Music" is out of date and cannot be selected. This version of the web app requires Plex Media Server 1.3.0 or higher. Use one of the links below to open an available, out of date server directly.
Ampache-Music (Unavailable)`
If you need any assistance with the bug it was straightforward to setup but utterly disappointing to use.
